# More option see https://github.com/DreamMaoMao/mango/wiki/
#
exec=pkill quickshell;quickshell
exec=pkill awww-daemon-wr;awww-daemon
exec=pkill mpris-proxy;mpris-proxy


source=./bind.conf
source=./theme.conf
source=./layout.conf
